---
- hosts: all
  tasks:
    - name: Clone a github repository
      git:
        repo: https://github.com/kushaggarwal/Devops-807.git
        dest: /home/ubuntu/
        clone: yes
        update: yes
