apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: application
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: busybox
        command:
        - sleep
        - "4000"
        imagePullPolicy: IfNotPresent
        name: busybox
